{% set name = "glue-jupyterlab" %}
{% set version = "0.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/glue_jupyterlab-{{ version }}.tar.gz
  sha256: 0033758d2cca09a30e8b3161b4dcc7f86cba70ae196572ae3dc52657d30a6dfe

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.7
    - pip
    - hatchling >=1.4.0
    - hatch-nodejs-version
    - hatch-jupyter-builder
    - jupyterlab >=4,<5
  run:
    - python >=3.7
    - jupyter_server >=1.21,<3
    - jupyter-collaboration >=1.0.0,<2.0.0
    - glue-core
    - glue-jupyter
    - yjs-widgets >=0.3.3,<0.4.0
    - ypywidgets >=0.4.0,<0.5.0

test:
  imports:
    - glue_jupyterlab
  requires:
    - pip
    - jupyterlab >=4,<5
  commands:
    # jupyter_server server extension
    - jupyter server extension list  # [unix]
    - jupyter server extension list 1>server_extensions 2>&1  # [unix]
    - cat server_extensions | grep "glue_jupyterlab.*OK"  # [unix]
    # labextensions
    - jupyter labextension list  # [unix]
    - jupyter labextension list 1>labextensions 2>&1  # [unix]
    - cat labextensions | grep "glue-jupyterlab.*OK"  # [unix]

about:
  home: https://github.com/QuantStack/glue-jupyterlab
  summary: 'Glue JupyterLab Extension'
  description: |
    Glue is an open-source data exploration tool that allows
    users to visualize and analyze data in a way that is
    intuitive and easy to understand. This JupyterLab
    extension brings Glue's data exploration capabilities
    directly into JupyterLab, allowing users to seamlessly
    analyze and visualize data without leaving their
    JupyterLab environment.
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  dev_url: https://github.com/QuantStack/glue-jupyterlab

extra:
  recipe-maintainers:
    - martinRenou
